[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %%H:%%M:%%S

[sqlalchemy]
sqlalchemy.url = driver://user:pass@localhost/dbname

[alembic]
script_location = migrations

sqlalchemy.url = driver://user:pass@localhost/dbname

version_location_template = %%s/versions

version_file_template = %%(rev)s_%%(slug)s

file_template = %%(rev)s_%%(slug)s

timezone = utc

truncate_slug_length = 40

compare_type = false

compare_server_default = false

include_object = lambda object, name, type_, reflected, compare_to: True

include_schemas = false

render_as_batch = false
